apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsync
  labels:
    app: rsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rsync

  template:
    metadata:
      labels:
        app: rsync
    spec:
      containers:
      - image: nexus-repo.cnfi.stratus.int.bell.ca/ubuntu:20.04
        name: rsync
        volumeMounts:
        - mountPath: /sys
          name: src
        - mountPath: /src
          name: src-1
        args:
        - -c
        - sleep 8640000
        command:
        - sh
        resources:
          limits:
            cpu: "100m"
            memory: "1Gi"
      nodeSelector:
        kubernetes.io/hostname: toroon63ivg
      volumes:
      - name: src
        persistentVolumeClaim:
          claimName: test-dev-1
          readOnly: true
      - name: src-1
        persistentVolumeClaim:
          claimName: test-dev-2
          readOnly: true