apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsync-2
  labels:
    app: rsync-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rsync-2

  template:
    metadata:
      labels:
        app: rsync-2
    spec:
      containers:
      - image: nexus-repo.cnfi.stratus.int.bell.ca/ubuntu:20.04
        name: rsync-2
        volumeMounts:
        - mountPath: /sys
          name: src
        - mountPath: /src
          name: src-1
        args:
        - -c
        - sleep 8640000
        command:
        - sh
        resources:
          limits:
            cpu: "100m"
            memory: "1Gi"
      nodeSelector:
        kubernetes.io/hostname: toroon63ivh
      volumes:
      - name: src
        persistentVolumeClaim:
          claimName: test-dev-3
          readOnly: true
      - name: src-1
        persistentVolumeClaim:
          claimName: test-dev-4
          readOnly: true